#convert number into binary,octal,hexadecimal..
import tkinter
def bin_oct_hex():
    n=int(t1.get())
    b=bin(n)
    o=oct(n)
    h=hex(n)
    t2.insert(0,b)
    t3.insert(0,o)
    t4.insert(0,h)

Window=tkinter.Tk()
Window.geometry("500x500")
l1=tkinter.Label(Window,text="enter number1:")
l1.grid(row=0,column=0)
t1=tkinter.Entry(Window,width="10")
t1.grid(row=0,column=1)
l2=tkinter.Label(Window,text="Binary:")
l2.grid(row=1,column=0)
t2=tkinter.Entry(Window,width="10")
t2.grid(row=1,column=1)
l3=tkinter.Label(Window,text="Octal:")
l3.grid(row=2,column=0)
t3=tkinter.Entry(Window,width="10")
t3.grid(row=2,column=1)
l4=tkinter.Label(Window,text="Hexadecimal:")
l4.grid(row=3,column=0)
t4=tkinter.Entry(Window,width="10")
t4.grid(row=3,column=1)
b1=tkinter.Button(Window,text="ok",fg="red",command=bin_oct_hex)
b1.grid(row=4,column=0)
Window.mainloop()
